### ISSUE TITLE
To coś wlasciwie robi?

### ISSUE THREAD

**Issue by FlyingMoustache** [Lenerox/test001#1]
https://github.com/Lenerox/test001/blob/480f2d45958ce21438bf8ef3d42c457d70e2654d/Program.cs#L4

**Comment by Lenerox** [comment]
Szczerze nie wiem ale żarówka ostrzegająca o możliwym błędzie zasugerowała, że to pomoże. (0_o)

**Comment by FlyingMoustache** [comment]
Oo
